name: Deploy Backend (Docker)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: namturne/weatherpick-app:latest

    
      - name: SSH and deploy backend container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 43.201.86.7
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[1] Stop old container"
            docker stop weatherpick-container || true
            docker rm weatherpick-container || true

            echo "[2] Pull latest image from Docker Hub"
            docker pull namturne/weatherpick-app:latest

            echo "[3] Run new container"
            docker run -d --name weatherpick-container \
              -p 8080:8080 \
              -p 443:443 \
              namturne/weatherpick-app:latest
